name: Dependabot

concurrency:
    group: Dependabot-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    pull_request:

jobs:
    Approve:
        runs-on: ubuntu-latest

        if: ${{ github.actor == 'dependabot[bot]' }}

        steps:
<<<<<<< HEAD
            - uses: dependabot/fetch-metadata@v2.0.1
=======
            - uses: dependabot/fetch-metadata@v2.1.0
>>>>>>> db7d42ab8f8e6fd4c630914f6d42001eb7b96d3b
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            - run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    Merge:
        runs-on: ubuntu-latest

        if: ${{ github.actor == 'dependabot[bot]' }}

        steps:
            - uses: dependabot/fetch-metadata@v2.1.0
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            - run: gh pr merge --auto --merge "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
